CREATE USER latest_user
  IDENTIFIED BY <NEW_PASSWORD>
  DEFAULT TABLESPACE SYSTEM
  QUOTA 20M on SYSTEM;
GRANT ALL PRIVILEGES TO latest_user;
GRANT CREATE SESSION, RESOURCE TO latest_user;
GRANT CREATE ANY TRIGGER TO latest_user;



/* simpler shortcut This is a SUPER user*/

CREATE USER new_user IDENTIFIED BY <NEW_PASSWORD>;
GRANT ALL PRIVILEGES TO new_user;
GRANT CREATE SESSION, RESOURCE TO new_user;
GRANT CREATE TABLESPACE TO new_user;




/*CREATE USER schema_1 IDENTIFIED BY <NEW_PASSWORD>;
GRANT CREATE SESSION, RESOURCE TO schema_1;
ALTER USER schema_1 QUOTA 100M ON users;  
*/
/*
CREATE USER <NEW_USER> IDENTIFIED BY <NEW_PASSWORD>;
GRANT CREATE SESSION, CREATE TRIGGER, CREATE TABLE, CREATE DATABASE LINK TO <NEW_USER>;
ALTER USER <NEW_USER> QUOTA 100M ON users;
GRANT READ, WRITE ON DIRECTORY data_pump_dir TO <NEW_USER>;
GRANT SELECT_CATALOG_ROLE TO <NEW_USER>;
GRANT EXECUTE ON DBMS_DATAPUMP TO <NEW_USER>;
GRANT EXECUTE ON DBMS_FILE_TRANSFER TO <NEW_USER>;
*/


/*create Tablespace*/

CREATE TABLESPACE uhub
  DATAFILE 'uhub.dat' 
    SIZE 10M
    REUSE
  AUTOEXTEND ON NEXT 10M MAXSIZE 200M;